# Generated by Django 4.0.6 on 2022-07-27 10:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stageir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('prenom', models.CharField(default='', max_length=150)),
                ('email', models.CharField(default='', max_length=150)),
                ('service', models.CharField(max_length=120)),
                ('debutstage', models.DateField()),
                ('fintage', models.DateField()),
                ('sexe', models.CharField(max_length=14)),
                ('cv', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'ppt', 'xlsx'])])),
                ('statu', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('nameMaître', models.CharField(default='', max_length=150)),
                ('Assiduité', models.CharField(default='', max_length=150)),
                ('Initiative', models.CharField(default='', max_length=150)),
                ('Communication', models.CharField(default='', max_length=150)),
                ('Esprit', models.CharField(default='', max_length=150)),
                ('Connaissances', models.CharField(default='', max_length=150)),
                ('Total', models.CharField(default='', max_length=150)),
                ('Observations', models.CharField(default='', max_length=1500)),
                ('statu', models.CharField(default='', max_length=150)),
                ('Stageir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.stageir')),
            ],
        ),
    ]
