# Generated by Django 4.0.6 on 2022-07-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='number',
            field=models.BigIntegerField(default=0),
        ),
    ]
