# Generated by Django 4.0.6 on 2022-07-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_rename_stageir_gestion_stageir_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestion',
            name='Stageir_id',
        ),
    ]
