# Generated by Django 4.0.6 on 2022-07-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_remove_gestion_stageir_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='Adresse',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='gestion',
            name='Option',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='gestion',
            name='Période',
            field=models.CharField(default='', max_length=150),
        ),
    ]
